#+title: How_to_prepare_data_for_machine_learning

* Data preparation process
1. Select data
2. Preprocess data
3. Transform data



** Step 1: Select data

Key question is considering what data we actually need to address the question or problem you are working on.

** Step 2: Preprocess data

Three common data preprocessing steps include -
- Formatting: might need to change the format (e.g., from relational to flat, etc.)
- Cleaning: cleaning data is the removal or fixing of missing data.
- Sampling: There might be more selected data than we actually need to work with.

** Step 3: Transform data

Three common transformations include -
- Scaling: the preprocessed data may contain attributes with mixtures of scales for various quantities such as dollars, kgs, and sales volume. Many machine learning methods need data attributes to have the same scale such as between 0 and 1 for the smallest and largest value for a given feature. Consider any feature scaling you need to perform.
- Decomposition: We might have features that are more useful to a machine learning method when split into the constituent parts.
- Aggregation: We may have features that can be aggregated into a single features that would be more meaningful to the problem we are trying to solve.
